### PR TITLE
 credmanager: support pluginConfigs ; other improvements

### PR DESCRIPTION
**Pull request by mightqxc**

### CODE REVIEW

**Comment by tmaeno** [comment]
I'm not sure if it is a good idea to introduce a new config file just for credmanager. It would be better if the json is integrated with queue_config.json, i.e. each queue could have a key 'credmanager' and a list of dictionaries. Each dictionary could define mod/classNames, setup, etc, of credmanger plugin. CredManager could loop over all queues and ignore duplicated dictionaries. Genrally this can be put in the template queue, so it doesn't have to be repeated in most cases. In the future, we might want to use a different token for each queue. Then it would be natural to define how to generate the token for each queue in queue_config.json.

**Comment by mightqxc** [comment]
I agree that config of site-specific credmanager plugins can be merged into queue_config.json ; I'll work on it later.

About those that are not site-specific (e.g. voms proxy, which I don't want to put in queue config since pandacon needs it), to avoid new config files, can we put the config in panda_harvester.cfg in json format? Say:


```
pluginConfigs = 
  [
    {
      "module": "pandaharvester.harvestercredmanager.no_voms_cred_manager",
      "name": "NoVomsCredManager",
      "configs": {
        "production": {
          "inCertFile": "/data/atlpan/proxy/atlpilo1RFC.plain",
          "outCertFile": "/data/atlpan/proxy/x509up_u25606_prod",
          "voms": "atlas:/atlas/Role=production"
        },
        "pilot": {
          "inCertFile": "/data/atlpan/proxy/atlpilo1RFC.plain",
          "outCertFile": "/data/atlpan/proxy/x509up_u25606_pilot",
          "voms": "atlas:/atlas/Role=pilot"
        }
      }
    }
  ]
  

```

In brief, credmanager can be configured in both panda_harvester.cfg and queue_config.json, in json format.

**Comment by tmaeno** [comment]
Sounds good.

**Comment by mightqxc** [comment]
Done. Ready to merge.

**Pull request merged**
