### PR TITLE
avoid writing to hardcoded /tmp location

### PR DESCRIPTION
**Pull request by rptaylor**
Fix https://github.com/HSF/harvester/issues/231

### CODE REVIEW

**Comment by rptaylor** [comment]
```
$ echo "tee ${TMPDIR:-/tmp}/wrapper-wid.log"
tee /tmp/wrapper-wid.log

$ TMPDIR=/data
$ echo "tee ${TMPDIR:-/tmp}/wrapper-wid.log"
tee /data/wrapper-wid.log
```

**Comment by rptaylor** [comment]
@fbarreir can you please take a look?

**Comment by fbarreir** [comment]
I'm running your branch. So far it looks OK - if I don't see any issues in the next hours, I'll merge.

**Comment by fbarreir** [comment]
The liveness probe that verifies if the log is moving was failing. It was also using the hardcoded /tmp. I've updated the liveness probe

**Pull request merged**
